apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/backend
  provider:
    name: sidhishruti22
  version: v1.0.2
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.a7dd532f80e8417ed33cf0c97328582847017895fc5146e499bdf4c94a9d17b5
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.0.2
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.0
  - access:
      localReference: sha256.6b2ca3c46ad91f9e1937c7cf6ad4778ad0d3cbd8eca5bc73c964bf7b4830341f
      mediaType: application/x-tgz
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.0.2
