apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podifydcom
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/podify
  version:
    semver: v1.1.9
    allowRollback: true
  repository:
    url: dcom-demo.int.repositories.cloud.sap
    secretRef:
      name: acreds
  references:
    expand: true
  
