apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podify
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/podify
  version:
    semver: ">=v1.0.1"
  repository:
    url: artefact-transfer-test.int.repositories.cloud.sap
    secretRef:
      name: acreds
  references:
    expand: true
  verify:
  - name: key
    publicKey:
      secretRef:
        name: publickey  

